/*
 * Copyright (C) 2006-2020 Istituto Italiano di Tecnologia (IIT)
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms of the
 * BSD-3-Clause license. See the accompanying LICENSE file for details.
 */

// Autogenerated by Thrift Compiler (0.12.0-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_SKILL_REQUEST_H
#define YARP_THRIFT_GENERATOR_SERVICE_SKILL_REQUEST_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <SkillAck.h>

class Skill_request :
        public yarp::os::Wire
{
public:
    // Constructor
    Skill_request();

    /**
     * request_ack  Get the ack of the skill.
     * return              The enum indicating the ack of the skill..
     */
    virtual SkillAck request_ack();

    /**
     * request_stop  Send a cmd_start skill.
     * return               void.
     */
    virtual void send_start();

    /**
     * send_stop  Send a CMD_STOP request to the skill.
     * return              void.
     */
    virtual void send_stop();

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_SKILL_REQUEST_H
