/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <SkillStatus.h>

int32_t SkillStatusConverter::fromString(const std::string& input)
{
    if (input=="SKILL_IDLE") {
        return static_cast<int32_t>(SKILL_IDLE);
    }
    if (input=="SKILL_RUNNING") {
        return static_cast<int32_t>(SKILL_RUNNING);
    }
    if (input=="SKILL_SUCCESS") {
        return static_cast<int32_t>(SKILL_SUCCESS);
    }
    if (input=="SKILL_FAILURE") {
        return static_cast<int32_t>(SKILL_FAILURE);
    }
    return -1;
}

std::string SkillStatusConverter::toString(int32_t input)
{
    switch(static_cast<SkillStatus>(input)) {
    case SKILL_IDLE:
        return "SKILL_IDLE";
    case SKILL_RUNNING:
        return "SKILL_RUNNING";
    case SKILL_SUCCESS:
        return "SKILL_SUCCESS";
    case SKILL_FAILURE:
        return "SKILL_FAILURE";
    }
    return "";
}
