/*
 * SPDX-FileCopyrightText: 2006-2021 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: BSD-3-Clause
 */

// Autogenerated by Thrift Compiler (0.14.1-yarped)
//
// This is an automatically generated file.
// It could get re-generated if the ALLOW_IDL_GENERATION flag is on.

#ifndef YARP_THRIFT_GENERATOR_SERVICE_SKILL_REQUEST_H
#define YARP_THRIFT_GENERATOR_SERVICE_SKILL_REQUEST_H

#include <yarp/os/Wire.h>
#include <yarp/os/idl/WireTypes.h>
#include <SkillStatus.h>

class Skill_request :
        public yarp::os::Wire
{
public:
    // Constructor
    Skill_request();

    /**
     * get_status  Get the SkillStatus of the skill.
     * return              The enum indicating the status of the skill.
     */
    virtual SkillStatus get_status();

    /**
     * start  Starts skill.
     * return               bool. True if the function ended correctly, false otherwise.
     */
    virtual bool start();

    /**
     * stop  Send a stop request to the skill.
     * return              void.
     */
    virtual void stop();

    // help method
    virtual std::vector<std::string> help(const std::string& functionName = "--all");

    // read from ConnectionReader
    bool read(yarp::os::ConnectionReader& connection) override;
};

#endif // YARP_THRIFT_GENERATOR_SERVICE_SKILL_REQUEST_H
